### ISSUE TITLE
replace_abbreviation_as_sentence_boundary causing high GC

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_segmenter#14]
The method `PragmaticSegmenter::AbbreviationReplacer#replace_abbreviation_as_sentence_boundary` chains eleven `.gsub` calls for each of the 23 SENTENCE_STARTERS, which each create a copy of the string and gc the old string. That's 253 GC'd strings for each call.

If replaced by `gsub!`this would avoid redundant copy/assign operations and speedup the method.

**Comment by airy** [comment]
indeed, thanks. i'll fix it when i got sometime.

**Comment by maia** [comment]
Thanks – once I realized that a method of mine spends > 50% of its time garbage collecting (using [tmm1 /stackprof](https://github.com/tmm1/stackprof)) I got suspicious, and as this method is run for each time `#segment` is called, it seems not completely irrelevant.
