### ISSUE TITLE
SENTENCE_STARTERS ignores defined language

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_segmenter#15]
`PragmaticSegmenter::AbbreviationReplacer::SENTENCE_STARTERS` is a constant that does not care about the defined language:

````ruby
SENTENCE_STARTERS = %w(A Being Did For He How However I In It Millions More She That The There They We What When Where Who Why)
````

I suggest it to be defined in PragmaticSegmenter::Languages::SomeLanguage , with an empty array as default.

If given the explanation/regex on how to analyze a dataset for appropriate sentence starters), I could provide the array for German.

**Comment by diasks2** [comment]
Thanks, great point. In that case this method would also change depending on the language https://github.com/diasks2/pragmatic_segmenter/blob/master/lib/pragmatic_segmenter/abbreviation_replacer.rb#L62-L92

**Comment by maia** [comment]
Oh, true! And besides the gsub chaining GC issue, one could refactor it to pass an array or hash containing the regexs to it, this way one could store these as a language constant too.

**Comment by diasks2** [comment]
Thanks for all your help and pointing out these issues. I really appreciate it! I'm kind of busy at the moment so I'm not sure when I can get to these...but if you would like to submit a pull request I would welcome it with open arms.

**Comment by maia** [comment]
@diasks2 I've just created a PR for the GC reduction. As for this issue here I don't yet understand enough of how pragmatic_segmenter works, but believe it should be enough to set `PragmaticSegmenter::AbbreviationReplacer::SENTENCE_STARTERS` as empty array and only overwrite it with the english words in `PragmaticSegmenter::Languages::English::AbbreviationReplacer` ?

**Comment by diasks2** [comment]
@maia Thanks for the PR on the GC reduction! As for this issue - yes, I think that would work.

**Comment by diasks2** [comment]
I think your PR (https://github.com/diasks2/pragmatic_segmenter/commit/f1cf4bd8dc8f4c771024f05f7181ba2d95ff6e47) closes this issue. Thanks for your help! Much appreciated! :+1:
