### ISSUE TITLE
How to run a ruby command?

### ISSUE THREAD

**Issue by lixiangnlp** [diasks2/pragmatic_segmenter#18]
Hi, I am a new one for Ruby. I have installed the pragmatic_segmenter with the command "sudo gem install pragmatic_segmenter". And could you give my a example rb file to run the tool for text? Because I met the following error when I use the command as your usage in the irb environment.

NameError: uninitialized constant PragmaticSegmenter
	from (irb):2
	from /usr/bin/irb:12:in `<main>'

**Comment by diasks2** [comment]
Hi @lixiangnlp 

After you open IRB, you first need to type the following command:
``require 'pragmatic_segmenter'``

Also, if you have an rb file that you want to run, you would need to include ``require 'pragmatic_segmenter'`` at the top of the file.

If you still have trouble getting it to work please let me know.

**Comment by Lanvin2219** [comment]
Hello,

I followed what you've written and I got this : 

irb(main):004:0> require 'pragmatic_segmenter'
NameError: uninitialized constant PragmaticSegmenter::Languages::Common::Abbreviation::Set
	from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:12:in `<module:Abbreviation>'
	from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:11:in `<module:Common>'
	from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:6:in `<module:Languages>'
	from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:5:in `<module:PragmaticSegmenter>'
	from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages.rb:5:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/segmenter.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):4
	from /usr/bin/irb:11:in `<main>'
