### ISSUE TITLE
Single characters get "cleaned" away

### ISSUE THREAD

**Issue by bwaide** [diasks2/pragmatic_segmenter#19]
single_character = 'a'
result = PragmaticSegmenter::Segmenter.new(text: single_character).segment
# result = []

**Comment by diasks2** [comment]
Thanks, should be fixed now (https://github.com/diasks2/pragmatic_segmenter/commit/4ded3f98f33c0f3b63661fe72a104f594fbc9e22). Let me know if you run into any other issues.
