### ISSUE TITLE
I have trouble running the program

### ISSUE THREAD

**Issue by Lanvin2219** [diasks2/pragmatic_segmenter#20]
Hello,

I've read this thread and followed what's written on it : 

https://github.com/diasks2/pragmatic_segmenter/issues/18

The problem is that I got this error message : 

irb(main):004:0> require 'pragmatic_segmenter'
NameError: uninitialized constant PragmaticSegmenter::Languages::Common::Abbreviation::Set
from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:12:in <module:Abbreviation>' from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:11:inmodule:Common'
from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:6:in <module:Languages>' from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:5:inmodule:PragmaticSegmenter'
from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages/common.rb:4:in <top (required)>' from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:inrequire'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require' from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/languages.rb:5:in'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require' from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:inrequire'
from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter/segmenter.rb:2:in <top (required)>' from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:inrequire'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require' from /var/lib/gems/2.3.0/gems/pragmatic_segmenter-0.3.9/lib/pragmatic_segmenter.rb:2:in'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in require' from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:inrescue in require'
from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in require' from (irb):4 from /usr/bin/irb:11:in'

Any help would be greatly appreciated.

Thanks

**Comment by diasks2** [comment]
Thanks for reporting this. I think it should be fixed now. I changed the order so that Set is required earlier (https://github.com/diasks2/pragmatic_segmenter/commit/ca99eff6c974a312756e703867a96d78221803c3). If you still have trouble please reopen this ticket. Thanks!

**Comment by Lanvin2219** [comment]
Thank you for being so reactive !
I'm not really familiar with Ruby and I didn't know what to do.
