### ISSUE TITLE
Test Suiite

### ISSUE THREAD

**Issue by artreven** [diasks2/pragmatic_segmenter#21]
Dear Kevin,

Thank you for your tool and for comparison with other tools. I was actually looking for test cases for WBD and how different approaches perform on them. Though I have found the results of testing, I have not found "a set of distinct edge cases" that you have created.
I would be glad to use your data for testing since Penn Treebank corpora is indeed too expensive for me.

Best,
Artem

**Comment by diasks2** [comment]
Hi Artem,

You can find the full test suite in this folder: https://github.com/diasks2/pragmatic_segmenter/tree/master/spec/pragmatic_segmenter/languages

Here is a [link](https://s3.amazonaws.com/tm-town-nlp-resources/golden_rules.txt) to a txt file with the distinct edge cases, and here is a [link](https://s3.amazonaws.com/tm-town-nlp-resources/golden_rules_rspec.rb) to a Ruby RSpec file.

Is that what you are looking for?

**Comment by artreven** [comment]
Kevin,

Yes, this is what I was looking for. Thank for a quick reply and for pointing the location.
