### ISSUE TITLE
Unexpected sentence break between abbreviation and hyphen

### ISSUE THREAD

**Issue by ronen** [diasks2/pragmatic_segmenter#26]
Hi again,

I came across this surprising behavior.  The first three of these are as expected (for comparison), but the last seems like a bug?

```
PragmaticSegmenter::Segmenter.new(text: "He has high level training", clean: false).segment 
    # => ["He has high level training"]

PragmaticSegmenter::Segmenter.new(text: "He has high-level training", clean: false).segment 
    # => ["He has high-level training"]

PragmaticSegmenter::Segmenter.new(text: "He has Ph.D. level training", clean: false).segment 
    # => ["He has Ph.D. level training"]

PragmaticSegmenter::Segmenter.new(text: "He has Ph.D.-level training", clean: false).segment 
    # => ["He has Ph.D.", "-level training"]
```

Thanks!

**Comment by diasks2** [comment]
Hi @ronen - thanks for finding that issue. I think this should fix it (https://github.com/diasks2/pragmatic_segmenter/commit/2a8d788f6c09a8deba89d35bde055fbaa358e3f7). I'll try to release a new version on ruby gems in the next 24 hours once I get back to my other computer.

**Comment by ronen** [comment]
cool, thanks for the quick response
