### ISSUE TITLE
Exclamation set apart by em dashes

### ISSUE THREAD

**Issue by ronen** [diasks2/pragmatic_segmenter#27]
Hi,

I came across this sentence:

    "Mix it, put it in the oven, and -- voila! -- you have cake."

And the exclamation mark is being treated as a sentence break:

    [
       "Mix it, put it in the oven, and -- voila!",
      "-- you have cake."
    ]

More generally it seems that a sentence should be able to contain an em dash clause that ends with an exclamation or question mark:

    "There are many -- oh so very many! -- similar cases."
    "Some can be -- if I may say so? -- a bit questionable."

You're the expert and I'm not, but I couldn't resist pondering a bit how to handle this :)  Here's what occurred to me...

A simple-minded rule would be to avoid a break if the subsequent sentence would start with a dash.  But I searched a bit and found that there are counterexamples, such as this line from Moby Dick:

> What do you see?—Posted like silent sentinels all around the town, stand thousands upon thousands of mortal men fixed in ocean reveries." 

So that would imply that a slightly less simple-minded rule would be to suppress a break due to a question or exclamation mark, if that mark is immediately followed by a dash *and* if there is a dash somewhere earlier in the sentence.

In any case, thanks as always for the great gem

**Comment by diasks2** [comment]
Hi ronen,

Thanks for adding this issue! I'm not sure how soon I'll be able to work on it as I am a little busy currently. On first glance though, it reminds me of single quotations, so my guess is that we can handle it similar to that (i.e. there are some cases where they appear inside of a sentence, some counter examples where only one appears, etc.).

Anyway, I'm confident there is a solution...just might be some time before I can work on it.

**Comment by ronen** [comment]
OK, no problem.  I've got my workaround in place (my client code does some pre-and post-processing anyway, so i added a check to for a sentence that starts with a dash etc.).

**Comment by diasks2** [comment]
I think this should handle your examples (https://github.com/diasks2/pragmatic_segmenter/commit/d6419d071d44675b7f9ed9403cb62e1068cf11d1), but let me know if any issues pop up.
