### ISSUE TITLE
Any Python equivalent of it?

### ISSUE THREAD

**Issue by nipunsadvilkar** [diasks2/pragmatic_segmenter#30]
@diasks2 : It's working very nice on few example I have tried on live demo. Could you provide any resource where I can get python equivalent of this repository? or else can you please guide or give general idea of `How should I proceed if I wish to make python one`?

**Comment by diasks2** [comment]
I'm not very familiar with python and python libraries, but I am sure they must have very good segmentation tooling. Generally speaking, python has a lot of tooling related to natural language processing. Maybe start here: https://spacy.io/

If you want to port this library to python, go for it. The code is MIT licensed: https://github.com/diasks2/pragmatic_segmenter/blob/master/LICENSE.txt

**Comment by nipunsadvilkar** [comment]
Thanks for your inputs.
Though ruby syntax and python syntax is somehow similar; I am not able to understand the source code fully but I can see few regex which I am familiar with. So could you brief me or give some guidelines on how should I proceed to port repo to python.

**Comment by diasks2** [comment]
I would start with the README and test suite. That includes the most important information. The tests were developed with linguists from that language, to try and tackle language specific segmentation issues. Other than that, unfortunately I can not be of much assistance, sorry.

**Comment by nipunsadvilkar** [comment]
@diasks2 : Thanks! will give a go at it
