### ISSUE TITLE
Breaks the sentence if start is abbreviation

### ISSUE THREAD

**Issue by nipunsadvilkar** [diasks2/pragmatic_segmenter#31]
If there is abbreviation at the start of the text, it breaks the sentence correctly and sometimes it doesn't.

My sample sentences were:
```
TAB. ECOSPRIN 75MG ONE TAB 10PM
```
Output:
```
TAB.
ECOSPRIN 75MG ONE TAB 10PM
```

whereas in the case of `Cal. is traditional abbreviation for California` it worked fine.

Is this because `lib/pragmatic_segmenter/languages/common.rb` has `cal` abbreviation in it?

**Comment by diasks2** [comment]
Yes, that is correct. It is because `cal` is specifically defined as an abbreviation. In your example sentence, what is `TAB.` an abbreviation for?

**Comment by nipunsadvilkar** [comment]
It's short-form for Tablet (TAB.) and I think it's not getting segmented right is fine since it's irrespective of normal English language and not used in day to day life except Medical domain.
Thanks!

**Comment by nipunsadvilkar** [comment]
Also, can you just enlighten me about what exactly `Cleaner.rb` script does if I set `clean: true`. I encountered one situation where it dropped few lines.

**Comment by diasks2** [comment]
A lot of `Cleaner.rb` (https://github.com/diasks2/pragmatic_segmenter/blob/master/lib/pragmatic_segmenter/cleaner/rules.rb) is related to formatting issues that come from OCR'ing PDF files (new lines in the middle of sentences, etc.). If you you found an issue where it is dropping lines, please open a GitHub issue with that and I can check it out. Thanks!
