### ISSUE TITLE
Not work!!!

### ISSUE THREAD

**Issue by sofinms** [diasks2/pragmatic_segmenter#33]
Brothers, this text not work:

Zur Pflanzengeographie Chinas China oder Sina sagen die einen, andere nennen es Eine einzige Ordnung ist fur das kosmische Leben . Diese letztgenannte Bezeichnung massgebend, und zwar ist es jene Ordnung, die ihm ist eine Ubersetzung des offiziellen chinesischen . 1'\' a die Kultur aufpriigt. " mcns, zhong kuo>. Der zweite-ebenfalls offizielle Riesig gross ist China, das Blutenland. \'on der . 1'\'amc des chinesischen Reichs lautet, Ostgrenze bis zur \Vestgrenze mnfasst es 6o Langen was so\'iel heisst wie, ssfumen>-oder, ssfutenlamf, ein grade, was einem Sechstel des Erdumfangs ent Name, der fur dieses Land der Nordhemisphare spricht; Yom Norden zum Suden sind es so Breiten durchaus berechtigt ist, denn hier ist die l.iclfiiltig grade. Das Klima ist kuhl-gemassigt im . 1'\'orden mit stc, artenreichste Flora der Alten \\'elt 1.orhandcn. ariden, wustenhaften Gebieten, im Suden hingegen Zudem sind Blumen, Baume und Straucher nicht gibt es tropische Regenwalder mit entsprechend ho nur Schmuck und Zierde, sondern sie sind seit ur her Luftfeuchtigkeit. Der Chomolongma im Eln alter Zeit mit Bedeutungstiefe 1erankert. Jahreszeit estmassi\' ist mit seinen 884H m der hochste Berg der liches Denken und Fuhlen ist in China lebendig Welt. Der tiefste Punkt in China liegt unter dem geblieben. Auch heute noch 11 eiss jedermann, wel Meeresni\'eau und misst -'54 m; er befindet sich in che Pflanzen unter den '\'ier Edlen> zu 1erstehen der Nahe des Aydingkolsees. Riesenhafte Berge, sind oder 11er d)ie Drei Freunde des Winters> sind."

**Comment by diasks2** [comment]
Hello, thanks for your interest in this gem. Could you please add the following to this issue:

1) What is the language of the text above?

2) Please provide smaller test cases from the large text above in the format of "original text" --> "desired result of segmented text"

**Comment by sofinms** [comment]
Brother, language of this text is German (de). 
Stop!!! This is not the text I was trying to process. Sory.
The text file is accessible by link: 
https://yadi.sk/d/jHmQh4Ix3Kasv3
When i try do this action:
ps = PragmaticSegmenter::Segmenter.new(text: text)
ps.segment
the script starts to eat a lot of RAM.  (0.3% -> 100%)

**Comment by sofinms** [comment]
The text file is accessible by reference)

**Comment by sofinms** [comment]
This comment form truncates some characters)

**Comment by sofinms** [comment]
Bro why are you silent?

**Comment by arbox** [comment]
@sofinms please be more patient and constructive.

P.S. "Bro" is not really a good start for a conversation.

**Comment by diasks2** [comment]
@sofinms - do you have an issue with how a German text was segmented or do you have an issue with the amount of RAM the gem is using when it runs?

If it is an issue with the segmentation of a text. Please provide a short example of a text that fails and what you believe the correct segmentation should be. Also, please provide this in your comment, not in an external link. Thanks!

**Comment by sofinms** [comment]
I tried to write the text in the comment, but the text was cleared of some characters ((Trusted text only in the link. I already do not care, now I use gem "tactful_tokenizer." I wanted to help you fix the bug ...
