### ISSUE TITLE
wrong segmentation

### ISSUE THREAD

**Issue by krsna-sentieo** [diasks2/pragmatic_segmenter#39]
the output for this text is wrong. In total there are 3 sentences in this
"Joe did not calculatingly set out to steal or defraud," his attorneys wrote in their submission to the judge. "Rather, he -- illegally -- shifted risk to unwitting investors by making false statements. This was not the Ponzi scheme it was made out to be in the media reports of his arrest and it was not a ’fictitious business’ where no tickets or ticket deals ever existed and money was simply stolen for selfish reasons."

**Comment by diasks2** [comment]
Hi @krsna-sentieo, thanks for using the gem. This is the intended behavior of this library. As this library was developed for segmenting texts used for translation, quotes are kept as one segment even if technically there are multiple grammatical sentences within the segment. This is mentioned in the README under *"What do you mean by opinionated?"*. I'll update the README though to make it more clear that this includes quotations in addition to sentences containing parenthesis.
