### ISSUE TITLE
Preserving characters between sentences?

### ISSUE THREAD

**Issue by cheerfulstoic** [diasks2/pragmatic_segmenter#42]
I tried looking in the docs and even in the code and this doesn't seem to be a feature.  So this is either a question or a potential feature request:

Is it possible to turn on a setting to preserve the spaces between sentences?  It would be ideal to be able to split sentences such that I can later re-create the entire document from the split parts.  Like if I had the string "What is a test?  This is a test!", I would get the array `['What is a test?  ', 'This is a test!']`

**Comment by maia** [comment]
@cheerfulstoic What would this feature offer over a simple `array.join(' ')`? Can you provide a use case? Thanks!

**Comment by cheerfulstoic** [comment]
I had thought about potentially storing text as fragments and then, when wanting the document again, bringing those fragments together.  The sentences split by `pragmatic_segmenter` (if I understand correctly) aren't always split by just one space (there might be multiple spaces / tabs / newlines / etc...) and being able to reproduce the original document could be useful rather than having to save a separate copy of the original.

Not that it's terribly difficult or expensive to save a separate copy.  I still haven't figured out exactly what I'll be doing yet and I might do just that, but I was curious what `pragmatic_segmenter` does / could offer

**Comment by maia** [comment]
pragmatic_segmenter doesn't really keep track how segments are separated, at current state this would need a major change of the code (and some refactoring first). As I'm sure you've also considered storing the original document and segmenting it on demand, I'm not sure what to suggest at the moment, but maybe someone else has an idea.

(I'm having a similar issue with pragmatic_tokenizer, sometimes I need to find a passage of the original document based on a few successive tokens, and I've pulled my hairs in trying to find a smart way to do so, but for now decided it's a problem I don't need to optimise immediately)

**Comment by cheerfulstoic** [comment]
Cool, that's fine and I'll close the issue for now (unless you'd like to actually address this at some point).  Another thought would be to have a mode which allows you to extract segments as tuples paired with the position offset in the document that the fragment came from.  Not sure how hard that would be (and again, not sure that I 100% want it yet ;) ).  Thanks!

**Comment by echan00** [comment]
If possible, it would be great if we can reopen this issue/feature

These two sentences will be segmented the same way, but are not really the same:
"I am a dog. You are a cat."
"I am a dog.  You are a cat."

For my case, I would like to recreate the original sentence: "I am a dog.  You are a cat." 
But it isn't possible because data is lost throughout the segmentation.

**Comment by echan00** [comment]
Forgot this was mentioned already: https://github.com/diasks2/pragmatic_segmenter/issues/60
