### ISSUE TITLE
Missing language Chinese (zh)

### ISSUE THREAD

**Issue by airy** [diasks2/pragmatic_segmenter#6]
there is a test for [chinese](https://github.com/airy/pragmatic_segmenter/blob/master/spec/pragmatic_segmenter_spec.rb#L2529) but language definition is missing.

**Comment by diasks2** [comment]
Yes, right now Chinese is just using the Common segmenter. We could definitely add a language specific class for Chinese as well, but right now it would just be falling back to Common as there is no Chinese specific functionality built in currently.

**Comment by airy** [comment]
actually missing [language code](https://github.com/diasks2/pragmatic_segmenter/blob/master/lib/pragmatic_segmenter/languages.rb#L23) for chinese makes  process_class & cleaner_class changes harder. i am gonna add chinese.

**Comment by diasks2** [comment]
Ok, sounds good. :+1:

**Comment by airy** [comment]
added in #8
