### ISSUE TITLE
Unable to segment text. Ruby 3.

### ISSUE THREAD

**Issue by malhotrachetan** [diasks2/pragmatic_segmenter#70]
Hi! So basic stuff. Trying to segment text but not able to. I get this error:

`/usr/local/lib/ruby/gems/3.0.0/gems/pragmatic_segmenter-0.3.22/lib/pragmatic_segmenter/processor.rb:37:in `block in split_into_segments': undefined method `apply' for "":String (NoMethodError)
        from /usr/local/lib/ruby/gems/3.0.0/gems/pragmatic_segmenter-0.3.22/lib/pragmatic_segmenter/processor.rb:37:in `map!'
        from /usr/local/lib/ruby/gems/3.0.0/gems/pragmatic_segmenter-0.3.22/lib/pragmatic_segmenter/processor.rb:37:in `split_into_segments'
        from /usr/local/lib/ruby/gems/3.0.0/gems/pragmatic_segmenter-0.3.22/lib/pragmatic_segmenter/processor.rb:30:in `process'
        from /usr/local/lib/ruby/gems/3.0.0/gems/pragmatic_segmenter-0.3.22/lib/pragmatic_segmenter/segmenter.rb:26:in `segment'`

I am on ruby ruby 3.0.0p0 and a Mac M1 machine.
Can anybody please help with this?

**Comment by diasks2** [comment]
This should be fixed now: https://github.com/diasks2/pragmatic_segmenter/pull/68
