### ISSUE TITLE
undefined local variable or method 'abbreviations'

### ISSUE THREAD

**Issue by diasks2** [diasks2/pragmatic_segmenter#9]
0.3.2/lib/pragmatic_segmenter/cleaner.rb:65:in `search_for_connected_sentences`

**Comment by diasks2** [comment]
@airy - no test to catch this, but I got this error when running in production. Should we get the abbreviations based on the language that is passed to the initialization method?

**Comment by airy** [comment]
@diasks2, every language module (should) have it's own or the included common language's abbreviations. which language is it?

**Comment by diasks2** [comment]
I was able to create a failing spec: https://github.com/diasks2/pragmatic_segmenter/commit/63e619c4ead6ae4a637587a1373dd9720943a6a8

**Comment by airy** [comment]
gotcha!

cleaner trying to access abreviations as instance variable, https://github.com/diasks2/pragmatic_segmenter/blob/master/lib/pragmatic_segmenter/cleaner.rb#L65

those constants/variables are/must be provided by the language module.

**Comment by airy** [comment]
[this](airy/pragmatic_segmenter/commit/e5b07a5c002e118d75da1921b424ef1e61fd227a) should fix the exception but not to pass the test.

**Comment by diasks2** [comment]
Thanks...but the link above is a 404 for me. Could you try to commit it again?

**Comment by airy** [comment]
ops! here is it: https://github.com/airy/pragmatic_segmenter/commit/e5b07a5c002e118d75da1921b424ef1e61fd227a

**Comment by diasks2** [comment]
Fixed: https://github.com/diasks2/pragmatic_segmenter/commit/c10ff3b4e02c7943ebc866a3e0d3aa5e21560d22
